language: python
python:
  - "2.7"
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
install:
  - travis_retry conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy
  - travis_retry pip install -r requirements.txt
  - travis_retry python setup.py develop
script: travis_wait py.test
cache: apt
